# docker-compose.yml

version: "3"

services:
  fastapi:
    image: jae99c/fastapi_docker_practice:first
    #command: uvicorn app.mainlist:app --host 0.0.0.0
    #volumes: 윈도우 에서는 볼륨쉐어 못함
    #  - .:/app
    ports:
      - "8000:8000"
    networks:
      - deploy_network
    container_name: fastapi
    
networks:
  deploy_network:
    driver: bridge